### ISSUE TITLE
Enhancement - Consistent GraphId and Gaffer Metadata Name Formats Across GaaS and Gaffer

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#122]
As User - I want to create a graph with the same graphId regex that Gaffer uses
So that - there is no extra regex's to consider and easier to create graphs

Deliverable 
- Have graphId for creating a Graph use the same regex rules as Gaffer - and use this as the main validation
- Have separate Kubernetes metadata regex validation 

Todo: 
Confirm with @t92549 how best to create metadata names

**Comment by macenturalxl1** [comment]
Hi @t92549 - the regex is different for Gaffer graphIds and Kubernetes metadata name label. We have been using graphIds for the metadata names currently and therefore the regex is limited to allow for both.

Example scenario:
as a User, I have my normal formats for Gaffer graphIds, so when I create a Graph, Kuberentes won't create it because of the metadata name regex

I was thinking - that gaas-rest should allow the same regex that Gaffer uses for graphId - and when using graphIds for metadata, simply reformat it (remove or replace invalid chars) so make a valid name label metadata 

Would that be better?

**Comment by t92549** [comment]
I think that is a good solution. Let people call their graphs what they usually can, and when it comes to making the Kubernetes resource we can mess with the name because the name is never used to get the `graphId`, an operation should be. Maybe just make sure there is a comment to make that clear when the resource name is generated. 
If the name is to be processed, then we need to ensure that duplicate Kubernetes resource names don't happen. This should probably be done by placing some random sequence at the end of the resource name. Perhaps `generateName` could be used for this suffix? https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#ObjectMeta

**Comment by macenturalxl1** [comment]
Hi thanks - I have seen this for some extra docs how generateName works: 
https://github.com/kubernetes-client/java/blob/a874e75af026d1833e3e35c3d54d4fbcfe99faf0/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1ObjectMeta.java#L266

**Comment by go159lab** [comment]
Hi @t92549 

Kubernetes uses metadata name to find the Graph. For instance Gaas-Resr API DELETE operation has the following format
..graph/{metadataName}

We always used graghId  ..graph/{graphId} for DELETE operaation
We never had issue because graphId and metadata name was same.

As we can't predict the final metadata name, I am not sure how formatting graphId or generate metadata name unique ID will help the user.

I think one solution is that we use validation which create Graph and Kubernetes share or are valid for both of them

I will look for a view other solutions.

Please let me know your suggestion

**Comment by t92549** [comment]
Yeah I didn't realise that the metadata name is indeed used for a lot of gaas operations. If that is the case then I think you are right, the name validation will have to consider both Gaffer and Kubernetes name restrictions and gaas graph Ids will have to be unique.

**Comment by t92549** [comment]
In this case then, I think the UI should do some kind of validation for simple things like spaces and capital letters.

**Comment by go159lab** [comment]
No changes needed for Gaas Rest Api side. So this ticket can be closed.
