### ISSUE TITLE
Create REST API capable of performing CRUD operations on K8s

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-experimental#31]
Create a basic REST API which can interact with Gaffer objects on the K8s REST API. At this point it doesn't have to worry about authentication.

As this will be a first step with no front end attached, it may be a good idea to include Swagger UI so that we can access it.

**Comment by rocky341** [comment]
Create has been implemented so the REST API can take input from the user (name and description) and create a CRD.
Delete has been implemented so that the REST API can delete a CRD given its name.
Read has been implemented so that the REST API can get all available CRDs.
Unit tests still need to be implemented but e2e testing has been done.

**Comment by b956022** [comment]
@d47853 Could you clarify if you actually want all CRUD operations? 

As it stands we have implemented **CREATE**, **READ** & **DELETE**. Do you want UPDATE as well? If so, what do you envision the UPDATE function doing?

**Comment by d47853** [comment]
Update should perform a helm upgrade on the Gaffer helm chart. However, I'd be alright with an initial contribution with just create, read and delete as long as there's an issue for it on Github
